fix: bump flask-sqlalchemy to 2.5.1
When running pytest, we encountered an error from SQLAlchemy:
AttributeError: 'LocalStack' object has no attribute '__ident_func__'

This looks to be due to an imcompatible version of Flask-SQLAlchemy installed.
Followed this StackOverflow suggestion: https://stackoverflow.com/a/72493087